let a = 1
try {
    a.toPrecision(450)
    console.log(no)
} catch (e) {
    console.log("error occurred")
    console.log(e.name)
    console.log(e.message) // 
}